messages:
  lack_of_ore: "&cНе хватает руды! &fНужно ещё &a{count} АР"
  lack_of_ar: "&cНе хватает денег! &fНужно ещё &a{count} АР"
  sell_success: "&fВы положили на счёт &a{count} АР"
  get_success: "&fВы вывели со счёта &a{count} АР"
  auto_add: "&fВам был автоматически начислен &a{count} АР"
  autosell_on: "&fВы &aвключили &fавтопродажу добываемой руды."
  autosell_off: "&fВы &cвыключили &fавтопродажу добываемой руды."
  pickupsell_on: "&fВы &aвключили &fавтопродажу подбираемой руды."
  pickupsell_off: "&fВы &cвыключили &fавтопродажу подбираемой руды."
  inventory_is_full: "&fВ ваш инвентарь &5не вместилось &fещё &a{count} АР"
  invalid_price: "&fКоличество &aАР &fдолжно быть положительным числом!"
  only_player: "&8[&5ARmoney&8] &cЭта команда может быть исполнена только игроком!"
  unknown_command: "&8[&5ARmoney&8] &fНеизвестная команда. Используй &5/ar help"
  dont_have_permission: "&8[&5ARmoney&8] &fУ вас &cнет прав &fна выполнение этой комманды!"
  config_reloaded: "&8[&5ARmoney&8] &aКонфиг перезагружен!"